name = "bastropcc-api"
main = "src/index.ts"
compatibility_date = "2024-03-14"
account_id = "b08d1a8316ab33834898d634d2e5db09"

[[d1_databases]]
binding = "DB"
database_name = "bastropcc-db"
database_id = "9dbb5eb4-34cc-442a-b752-b0999469da39"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "4bf424f8e7074caaa715cde4e27848d2"

[vars]
CORS_ORIGIN = "https://bastropcc.pages.dev,https://bastropcc-admin.pages.dev"
ENVIRONMENT = "production"
