ALTER TABLE events ADD COLUMN date TEXT;
ALTER TABLE events ADD COLUMN time TEXT;
ALTER TABLE events ADD COLUMN org TEXT;
ALTER TABLE events ADD COLUMN county TEXT;
ALTER TABLE events ADD COLUMN type TEXT;
